extends SceneTree
## Regenerate the Inspector tuning inventory with --headless --script.

var rows: PackedStringArray = []
var seen: Array[Resource] = []


func _initialize() -> void:
	call_deferred("run")


func record_exports(object: Object, path: String) -> void:
	for property in object.get_property_list():
		if not (property.usage & PROPERTY_USAGE_SCRIPT_VARIABLE and property.usage & PROPERTY_USAGE_EDITOR):
			continue
		var value: Variant = object.get(property.name)
		var location := path + " / " + String(property.name)
		if value is Resource and value.get_script() != null:
			if value not in seen:
				seen.append(value)
				record_exports(value, location)
		elif value is Array:
			for i in value.size():
				if value[i] is Resource and value[i].get_script() != null:
					record_exports(value[i], "%s[%d]" % [location, i])
		elif typeof(value) in [TYPE_BOOL, TYPE_INT, TYPE_FLOAT, TYPE_VECTOR2, TYPE_VECTOR2I, TYPE_VECTOR3, TYPE_RECT2, TYPE_COLOR, TYPE_PACKED_INT32_ARRAY, TYPE_PACKED_COLOR_ARRAY, TYPE_DICTIONARY]:
			if property.name in [&"captions", &"balloons", &"comments", &"sound_effects", &"subtitles", &"endings"]:
				continue
			rows.append("| `%s` | `%s` |" % [location, str(value).replace("|", "\\|")])


func visit(node: Node) -> void:
	record_exports(node, String(node.get_path()).trim_prefix("/root/Main/"))
	if node is Light3D:
		for key in ["light_energy", "light_color", "shadow_bias", "shadow_normal_bias"]:
			rows.append("| `%s / %s` | `%s` |" % [String(node.get_path()).trim_prefix("/root/Main/"), key, str(node.get(key))])
		var keys := ["spot_range", "spot_angle", "spot_attenuation", "spot_angle_attenuation"] if node is SpotLight3D else ["omni_range", "omni_attenuation"]
		for key in keys:
			rows.append("| `%s / %s` | `%s` |" % [String(node.get_path()).trim_prefix("/root/Main/"), key, str(node.get(key))])
	if node is Camera3D or node.name in [&"Torch", &"Beam", &"Paperweight", &"Paperweight2", &"Paperweight3", &"DeskLamp"]:
		rows.append("| `%s / position` | `%s` |" % [node.name, str(node.position)])
		rows.append("| `%s / rotation_degrees` | `%s` |" % [node.name, str(node.rotation_degrees)])
		if node is Camera3D:
			rows.append("| `Camera3D / size` | `%s` |" % node.size)
	for child in node.get_children():
		visit(child)


func run() -> void:
	# Use the authored desktop size for responsive camera/layout defaults.
	root.size = Vector2i(1280, 720)
	root.content_scale_size = Vector2i(1280, 720)
	var scene: Node3D = load("res://scenes/main.tscn").instantiate()
	root.add_child(scene)
	await physics_frame
	visit(scene)
	var result: Control = load("res://scenes/ui/comic_result.tscn").instantiate()
	record_exports(result, "ComicResult")
	result.free()
	var mood := Control.new()
	mood.set_script(load("res://scripts/ui/mood_meter.gd"))
	record_exports(mood, "ComicResult / MoodMeter")
	mood.free()
	record_exports(NewsroomTheme.style, "data/ui/default.tres")
	var file := FileAccess.open("res://docs/tuning.md", FileAccess.WRITE)
	file.store_string("# Campaign tuning inventory\n\nGenerated by `tools/dump_tuning.gd` from scene and Resource defaults.\nEdit these settings in the Godot Inspector; coordinates use Godot world units.\nCampaign Resource entries show per-case optics and tool overrides.\nThe shared paperweight meshes use radius 0.27 (sphere) and 0.29 (base),\nwith heights 0.54 and 0.09 before the tutorial’s 1.5 scale override in `scenes/tools/paperweight.tscn`.\n\n| Inspector location / property | Current value |\n| --- | --- |\n" + "\n".join(rows) + "\n")
	quit()
